spring:
  datasource:
    url: jdbc:mysql://produrl:3306/innovoices # ?createDatabaseIfNotExist=true # &allowPublicKeyRetrieval=true
    username: prod
    password: 123
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  sql:
    init:
      mode: always


